### ISSUE TITLE
Local Development

### ISSUE THREAD

**Issue by CaoKha** [opensourcecheemsburgers/RustyTube#22]
Hi Stephen,

I try to run the project in local by running this command
```bash
cargo tauri dev
```
but the wasm panicked in the console
```
panicked at /rust/deps/dlmalloc-0.2.5/src/dlmalloc.rs:1182:13:
assertion failed: psize <= size + max_overhead 
```
and the InstanceSelectDropdown component doesn't appear.

Is there a way to make the project work in local machine? I'm really interested to improve your project.

**Comment by opensourcecheemsburgers** [comment]
Hi :) What platform are you trying to compile on?

**Comment by CaoKha** [comment]
I'm on Linux.

**Comment by opensourcecheemsburgers** [comment]
I have added build instructions to the [`README.md`](https://github.com/opensourcecheemsburgers/RustyTube).

Try those and let me know if the error persists.

**Comment by CaoKha** [comment]
I did follow your PKGBUILD and compile successfully your project but when I started the local server (with `trunk serve` or `cargo tauri dev`) I got this:
![no_server_found](https://github.com/opensourcecheemsburgers/RustyTube/assets/43724342/4f2f291f-31c8-4a35-a6e6-6927db16e175)
Maybe because of you are using YouTube API?

**Comment by opensourcecheemsburgers** [comment]
I am able to replicate this. Not sure what is causing it though.

RustyTube uses the Invidious API.

**Comment by opensourcecheemsburgers** [comment]
This was a nightly error. Thanks for the heads up :)

Fixed in this [commit](https://github.com/opensourcecheemsburgers/RustyTube/commit/08ead2d5b9623df48502528a8cd8243c751f5dec).
