### ISSUE TITLE
Importing subscriptions doesn't work (Firefox/rustytube.rs)

### ISSUE THREAD

**Issue by aalhitennf** [opensourcecheemsburgers/RustyTube#3]
Trying out the app at rustytube.rs with Firefox. Import subscription from json file, i get this warning in browsers console and nothing else happens:

```
Attempted to update a signal after it was disposed.
warning happened here: /home/winton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_server-0.5.7/src/action.rs:368:29
```

**Comment by opensourcecheemsburgers** [comment]
How many subscriptions do you have? Have you tried changing your Invidious instance in the top left?

The UI needs to show a placeholder when the import is successful and is loading videos but I couldn't get it to work properly.

**Comment by opensourcecheemsburgers** [comment]
Importing works in my Firefox and the aforementioned error seems to be unrelated to the issue. Closing for now.
