### ISSUE TITLE
macos build has some errors and run failed.

### ISSUE THREAD

**Issue by dezbracaty** [opensourcecheemsburgers/RustyTube#31]
# Env
machine: Apple M1 Pro
system: macos 14.2.1 (23C71)

# 1 
when I build this program and run "cargo run --bin RustyTube",
command line output is :

> error: proc macro panicked
 --> src-tauri/src/main.rs:6:8
  |
6 |         .run(tauri::generate_context!())
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: The `distDir` configuration is set to `"../frontend/dist"` but this path doesn't exist
error: could not compile `RustyTube` (bin "RustyTube") due to 1 previous error 

when I change "../frontend/dist" to ""../frontend" in /src-tauri/tauri.conf.json ,this error disappear.

# 2 
running program by "cargo run --bin RustyTube"

output is below:

> warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
warning: /Users/allen/Projects/RustProjects/RustyTube/Cargo.toml: unused manifest key: workspace.target
warning: RustyTube v0.1.1 (/Users/allen/Projects/RustProjects/RustyTube/src-tauri) ignoring invalid dependency `tauri-bindgen` which is missing a lib target
   Compiling RustyTube v0.1.1 (/Users/allen/Projects/RustProjects/RustyTube/src-tauri)
warning: crate `RustyTube` should have a snake case name
  |
  = help: convert the identifier to snake case: `rusty_tube`
  = note: `#[warn(non_snake_case)]` on by default
warning: `RustyTube` (bin "RustyTube") generated 1 warning
    Finished dev [unoptimized] target(s) in 7.21s
     Running `target/debug/RustyTube`

and program is white :
![image](https://github.com/opensourcecheemsburgers/RustyTube/assets/20027937/c017055a-0751-4c50-8835-19d9c90672c9)

**Comment by dezbracaty** [comment]
So , Can macos build this software and run it ?

**Comment by opensourcecheemsburgers** [comment]
Changing dist dir is not necessary. You need npm or pnpm.

1. `cd frontend` 
2. `npm i` or `pnpm i`. 
3. `cd ../`.
4. `cargo tauri dev` 

If it works, the layout may look weird because webkit has bad support for grid layout which is why there was no Linux release for the latest update. This may change when I have the time to change the layout back to flex with responsive design. 

Note: I have tried compiling RustyTube in a Mac VM before but got [this](https://github.com/godotengine/godot/issues/74512) kind of error.

**Comment by dezbracaty** [comment]
> Changing dist dir is not necessary. You need npm or pnpm.
> 
> 1. `cd frontend`
> 2. `npm i` or `pnpm i`.
> 3. `cd ../`.
> 4. `cargo tauri dev`
> 
> If it works, the layout may look weird because webkit has bad support for grid layout which is why there was no Linux release for the latest update. This may change when I have the time to change the layout back to flex with responsive design.
> 
> Note: I have tried compiling RustyTube in a Mac VM before but got [this](https://github.com/godotengine/godot/issues/74512) kind of error.

Thanks for your reply ! It truly works . I will close this question and thank you again!
