### ISSUE TITLE
aur link is empty

### ISSUE THREAD

**Issue by asukaminato0721** [opensourcecheemsburgers/RustyTube#4]
https://aur.archlinux.org/packages/rustytube

![image](https://github.com/opensourcecheemsburgers/RustyTube/assets/30024051/31b34528-212f-4aab-b50f-fc7c8afbf28a)

I made a -bin package, https://aur.archlinux.org/packages/rustytube-bin

**Comment by opensourcecheemsburgers** [comment]
Installed easily on my desktop (I use Arch btw). Thanks :)
